# Generated by Django 5.0 on 2024-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyAcad_Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
