# Generated by Django 5.0 on 2024-09-14 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyAcad_Data', '0002_all_course_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='title',
        ),
        migrations.AddField(
            model_name='certification',
            name='course_comp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='course_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
