# Generated by Django 5.0 on 2024-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyAcad_Data', '0003_remove_certification_title_certification_course_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
